### ISSUE TITLE
e is not a constructor 

### ISSUE THREAD

**Issue by SaiReddy-A** [GMOD/jbrowse-plugin-msaview#24]
Hi, 
I was trying to develop and integrate this plugin in our jbrowse2 but I'm not sure if I'm doing something wrong or there's an issue with this plugin. I would really appreciate it if you could help me.
So, basically this is what I've done.
...
git clone https://github.com/GMOD/jbrowse-plugin-msaview.git
cd jbrowse-plugin-msaview
yarn 
yarn start
...
it started serving on http://localhost:9000 
Whereas our jbrowse web was running on http://206.XX.XX.XX:5000/
So, I opened jbrowse web to http://206.XX.XX.XX:5000/?config=http://localhost:9000/config.json

I got the following error

![jb2](https://user-images.githubusercontent.com/60203610/113332301-ff6ae780-92ee-11eb-9453-1857e7019c26.jpg)

Thank you for your help!!
Sai

**Comment by cmdcolin** [comment]
Hi there :)

Do you have info about which jbrowse 2 version you are using?  I think I can reproduce the error for example if I change my demo link to

https://s3.amazonaws.com/jbrowse.org/code/jb2/v1.0.3/index.html?config=https://unpkg.com/jbrowse-plugin-msaview/dist/config.json&session=share-BVmmEYAoAv&password=SuQaN

But v1.0.4, and v1.1.0 (latest) should work

https://s3.amazonaws.com/jbrowse.org/code/jb2/v1.0.4/index.html?config=https://unpkg.com/jbrowse-plugin-msaview/dist/config.json&session=share-BVmmEYAoAv&password=SuQaN

https://s3.amazonaws.com/jbrowse.org/code/jb2/v1.1.0/index.html?config=https://unpkg.com/jbrowse-plugin-msaview/dist/config.json&session=share-BVmmEYAoAv&password=SuQaN

This is definitely a very new plugin area and it builds off the modularized component here https://github.com/GMOD/react-msaview

It doesn't have a ton of actual integration with jbrowse 2 itself currently (so on some level, at least at the moment, there is not a ton of value for it being run inside of jbrowse 2) but I want to make features like clicking on gene annotation->launches a MSA for that gene and related species

**Comment by SaiReddy-A** [comment]
Hi, 
I'm using version 1.0.3 and I see that you are getting the same error with 1.0.3. 
I guess I'll have to update my jbrowse instance and see if it works. 
You guys are doing an amazing work and It's really exciting to know there'll be more features. 

Thank you!!
