### ISSUE TITLE
Failed to load UMD bundle for MSAView, JBrowsePluginMSAView is undefined in Dev version used on a local browser

### ISSUE THREAD

**Issue by pdtouch** [GMOD/jbrowse-plugin-msaview#28]
```
yarn --version
1.22.19
jbrowse --version
@jbrowse/cli/2.5.0 linux-x64 node-v20.2.0
cd ~/jbrowse-components/products/jbrowse-web
yarn start

```

I am trying to use react/msaview plugin for browsing aligned proteins dataset. When I use the (Dev version locally) 
I can view JBRowse app on the browser at [localhost:3000](http://localhost:3000/) but I am unable to install the MSAView plugin, clicking on install in the plugin store panel does not add  MSA view. When I include the "plugin" in config.json, I get an error message:
`Error: Failed to load UMD bundle for MSAView, JBrowsePluginMSAView is undefined
`
The Desktop AppImage does not show this problem, installs the MSAview plugin OK, but is slow for browsing the sequences in the MSA viewer.
Is there anything I can do to get the plugin installable for (http://localhost/) access or if there is a way to use JBrowse to browse MSAs  faster.

**Comment by cmdcolin** [comment]
it appears you are using the 'dev version' e.g. a clone of our git repo, can you type e.g. "git rev-parse HEAD"  to show what commit you are on AND/OR update to the latest "main" branch?

also I am curious about the slowness you see, do you have an example MSA file that I could try out to reproduce?

**Comment by pdtouch** [comment]
```
git rev-parse HEAD
c2454aa9e1b62563da513dd3c91d0ff0dd47de45

```

**Comment by cmdcolin** [comment]
the snippet in the plugins.json may want to be 

```json
{
    "name": "MsaView", // not MSAView
    "url": "https://unpkg.com/jbrowse-plugin-msaview/dist/jbrowse-plugin-msaview.umd.production.min.js"
}
```

the issue where installing from plugin store was not working was a good catch and I fixed it on latest main

**Comment by pdtouch** [comment]
Thanks ! Works perfectly.
