### ISSUE TITLE
Previous BLAST hits missing mouseover

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-plugin-msaview#31]
from in progress dev work on NCBI BLAST->MSA

**Comment by ihh** [comment]
Exciting :)

**Comment by cmdcolin** [comment]
indeed. I'll send you a full demo very shortly...basically have a workflow where we can launch a BLAST query, and use that to gather a multiple sequence alignment....avoids this sort of challenge where we needed a specific meticulously prepped MSA from the UCSC for example that i've used in previous demos. makes it much more usable on basically any dataset. will send soon!

**Comment by cmdcolin** [comment]
removed the "previous blast hits" functionality for now. could revisit if there is interest
