### ISSUE TITLE
Refactoring wide canvas implementation

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-plugin-msaview#4]
Current implementation of abrowse makes a wide canvas with offscreen areas and paints in that area. Should probably use block based style or screen width canvas

Running canvas.toDataURL() demonstrates

![download](https://user-images.githubusercontent.com/6511937/104355493-5de2af80-54d0-11eb-9e91-c94dbf0ca30c.png)

**Comment by ihh** [comment]
Intent of offscreen rendering was so that dragging didn't reveal blank areas. Agree that block-based style would handle this while minimizing unnecessary renders.

**Comment by cmdcolin** [comment]
I think I was incorrect and thought the canvas width was the size of the whole alignment but see now it is just the width of the viewport+the extra ratio, so the concern in this PR is tempered. We may still work on minimizing unnecessary rerenders

**Comment by cmdcolin** [comment]
Block based version tentatively merged to master here...will be iterating on it
